package com.nanangmaxfi.jetmoviesubs.model

object FakeMovieDataSource {
    val dummyMovies = listOf(
        Movie(1,
            "Black Adam",
            "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
            "pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
            "2022-10-19",
            7.3,
            2496
        ),
        Movie(2,
        "The Guardians of the Galaxy Holiday Special",
        "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
        "8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
        "2022-11-25",
            7.479,
            603
        ),
        Movie(3,
        "Troll",
        "Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?",
        "9z4jRr43JdtU66P0iy8h18OyLql.jpg",
        "2022-12-01",
            6.894,
            329
        ),
        Movie(4,
        "Black Panther: Wakanda Forever",
        "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
        "ps2oKfhY6DL3alynlSqY97gHSsg.jpg",
        "2022-11-09",
            7.541,
            1206,
        ),
        Movie(5,
        "Warriors of Future",
        "When a meteor carrying a destructive plant strikes the world, a suicide squad is given hours to save their post-apocalyptic city from total collapse.",
        "2l9LbxBSkJseoxYcIJjclnmxyq.jpg",
        "2022-08-05",
            7.44,
            116
        ),
        Movie(6,
        "Disenchanted",
        "Disillusioned with life in the city, feeling out of place in suburbia, and frustrated that her happily ever after hasn’t been so easy to find, Giselle turns to the magic of Andalasia for help. Accidentally transforming the entire town into a real-life fairy tale and placing her family’s future happiness in jeopardy, she must race against time to reverse the spell and determine what happily ever after truly means to her and her family.",
        "4x3pt6hoLblBeHebUa4OyiVXFiM.jpg",
        "2022-11-16",
            7.268,
            490
        ),
        Movie(7,
        "Lyle, Lyle, Crocodile",
        "When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.",
        "irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg",
        "2022-10-07",
            7.801,
            136
        ),
        Movie(8,
        "Slumberland",
        "A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, with the hope that she will be able to see her late father again.",
        "f18kgonrgr8YvEuvshExS4XBGL8.jpg",
        "2022-11-09",
            7.823,
            348
        ),
        Movie(9,
        "Scrooge: A Christmas Carol",
        "On a cold Christmas Eve, selfish miser Ebenezer Scrooge has one night left to face his past — and change the future — before time runs out.",
        "nOrnzHn9SCF6JTXfX02eSPyAAXL.jpg",
        "2022-11-18",
            7.7,
            39
        ),
        Movie(10,
        "Avatar: The Way of Water",
        "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
        "t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        "2022-12-14",
            0.0,
        0
        ),
        Movie(11,
        "Lady Chatterley's Lover",
        "Unhappily married aristocrat Lady Chatterley begins a torrid affair — and falls deeply in love — with the gamekeeper on her husband's country estate.",
        "aSgl2DxPG3DuQXoaHr500KeULmT.jpg",
        "2022-09-02",
            6.943,
        44
        )
    )
}